### ISSUE TITLE
Nuget error for adrotator wp8

### ISSUE THREAD

**Issue by jamesfdickinson** [Adrotator/AdrotatorV2#11]
Attempting to resolve dependency 'AdDuplexWP8 (≥ 2.8.0.3)'.
The remote name could not be resolved: 'az320820.vo.msecnd.net'

**Comment by SimonDarksideJ** [comment]
I need to update the NuGet to remove the version check.  That way it will always get the latest.  I guess AdDuplex have removed that version

**Comment by SimonDarksideJ** [comment]
Right, got a patch fix version of AdRotator V2 ready, should publish in a day or so

**Comment by SimonDarksideJ** [comment]
RIght, just about ready to publish the NuGet, sorry it took a while longer.
We had to update the implementation for the latest version of AdDuplex and a few other providers.
