### ISSUE TITLE
Problem showing ads in released version of my app

### ISSUE THREAD

**Issue by jklevela** [Adrotator/AdrotatorV2#12]
Hi,
I've added the AdRotator V2 to my solution and configured it to use a Remote config.

When deployint the app to my phone it Works fine, but when I uploads to the store and then install on my phone, it does not show any ads.
The logging when deployed directly to my phone:
"Trying provider AdDuplex
Ad created for provider AdDuplex
Ad created for provider AdDuplex
Ads served for: AdDuplex
Ad failed request for: AdDuplex
Ads failed request for: AdDuplex
Trying provider None
No Ads available"

Logging when installed from the store:
"Trying provider None
No Ads available"

Same app, build and config...

Please help.

**Comment by SimonDarksideJ** [comment]
Hmm, that does sound odd.
We usually recommend shipping a local config file in case there are issues for the device reaching your remote config.
All the test example apps so far do not have issues reaching remote config, check for Starter 2D / 3D in the store.

Can you confirm you only have AdDuplex configured as your provider in the remote configuration and are you using the latest AdDuplex client (check for updates in NuGet in your solution)

**Comment by SimonDarksideJ** [comment]
@jklevela have you managed to resolve your problem?  We've tested the V2 control thoroughly and have been unable to replicate it
