### ISSUE TITLE
Adrotator is not displaying ads on released app.

### ISSUE THREAD

**Issue by Ezapphire** [Adrotator/AdrotatorV2#14]
Sorry about my bad english...

I use Adrotator V2.

When I'm developing, the ads are displayed correctly at 100% fill rate with a exception of pubCenter ...

then, when i publish the app and download in my cellphone or another phone, no ads are shown..

i´m skipping some important step?

here is a sample of the code.
https://www.dropbox.com/sh/mmdoem4m4r6p67l/AACNsbpuWUNxFi4-gD9C558Va

my defaultconfig..
http://clovercloud.azurewebsites.net/ads/defaultAdSettings.xml

**Comment by johanlindfors** [comment]
Has this been resolved yet?

**Comment by SimonDarksideJ** [comment]
Apologies, due to work load I've been unable to look at this yet.
I'll check on it this week.

**Comment by SimonDarksideJ** [comment]
@Ezapphire is still an issue? we've been unable to replicate your problem here.
