### ISSUE TITLE
AdRotator v2.1on WP8 doesn't rotate ad providers

### ISSUE THREAD

**Issue by LukApps** [Adrotator/AdrotatorV2#15]
Hi, while testing my app on my dev phone I noticed that AdRotator doesn't rotate ad providers. I mean that if the first ad served comes from AdDuplex, all next ads come from AdDuplex as well. On the other hand, if the first ad served comes from PubCenter, all next ads come from PubCenter too. I thought that it would rotate ad providers on the basis of probabilities provided in the configuration files, but it seems that the probabilities are used only at app startup to draw a one and only ad provider. Is it an intended bahaviour of AdRotator?

My configuration is very simple:

```
    <adRotator:AdRotatorControl
        x:Name="AdRotator"
        xmlns:adRotator="clr-namespace:AdRotator;assembly=AdRotator"
        AdHeight="80"
        AdWidth="480"
        LocalSettingsLocation="defaultAdSettings.xml"
        AutoStartAds="True" />
```

[...]

```
<PubCenter AppId="test_client" SecondaryId="Image480_80" Probability="50"/>
<AdDuplex AppId="101643" Probability="50"/>
```

[...]

My other remark is that DefaultAdType property doesn't exist.

Regards,
Luke

**Comment by SimonDarksideJ** [comment]
The probability should be recalculated on each ad serving.  But I'll check in to this

**Comment by LukApps** [comment]
@DDReaper 
After adding 2 new ad providers (Smaato and AdMob) I don't see much improvement in that matter.
At app startup AdRotator indeed tries all 4 providers. However after finding one that serves ads (usually AdDuplex or Smaato) it sticks to it for a long period of time serving ads. But if it sticks to AdMob, it constantly shows the very firs ad displayed.
If the first working ad provider fails (let's say AdDuplex, however it is very strange that it fails at all), AdRotator tries all providers except for AdDuplex, which provide no ads. The control remains black and empty forever (shouldn't it collapse, anyway?). Then from time to time I observe "Ads served for: Smaato" debug, which doesn't reflect the reality. Perhaps setting a default ad provider could help in this scenario, but since DefaultAdType property isn't accessible in code/xaml, I can't do it (is it possible in the config file?).
Any ideas what could be wrong and how to fix it?
Should I try v1 instead?

**Comment by SimonDarksideJ** [comment]
The selection logic is the Same in both but there's no harm in trying.
Just be sure to update the provider dll's from the NuGet to the latest versions.
Don't remove any as the limitation with v1 is that you need them all

**Comment by SimonDarksideJ** [comment]
Right, I did some testing and it will rotate ads based on the probability set and will swap out the ads if another provider is selected.
Although the randomness doesn't feel that random.  Will have a look at the probability logic to see if it can be improved.

It's currently like this:
Iterator (Total of provider probabilities / \* random double value) < probability value

So it loops through the providers sequentially to see if their probability is within the random tolerance.

Could possibly improve this via:
- Random sampling instead of iterative
- alternate probability selection

Will see if it can be improved.

**Comment by SimonDarksideJ** [comment]
Ok, in the next update we have improved the randomness of the ad selection making it more unlikely that the same provider will be chosen even if the providers have the same probability.

It is still a probability however, so dependant on the gods of randomness.

In the future we will also be introducing the AdOrder and AdGroups which will give you greater control over the sequence of ad providers
