### ISSUE TITLE
AdMob have updated their format of the Ad Unit Id and it doesn't work with AdRotator.

### ISSUE THREAD

**Issue by johanlindfors** [Adrotator/AdrotatorV2#17]
Old format: a141234567890ab
New format: ca-app-pub-xxxxxxxxxxxxxxxx/nnnnnnnnnn 

When adding this to the latest version all ad requests for admob fails. But if I ad the actual AdMob AdView to the project, the request succeeds. My guess is that the request fails due to special character '/' included in the new format.

Any ideas on how to solve this matter?

**Comment by johanlindfors** [comment]
My bad, I accidentially had a space character in the end of the ad unit id which caused the invalid request. Now it works just fine! Sorry!

**Comment by SimonDarksideJ** [comment]
Lol, but I like those kinds of errors, not mine :dancer: 
Glad you got it sorted

**Comment by SimonDarksideJ** [comment]
Note, we are updating to their latest control which did have some breaking changes, should be released soon
