### ISSUE TITLE
No ads or test-placeholders shown at all

### ISSUE THREAD

**Issue by garv3** [Adrotator/AdrotatorV2#21]
Hello everyone,

I just implemented v2 of Adrotator and to my Windows Phone 8 project but no ads are displayed!
I've set IsTest="True" in xaml but even the placeholders are not displayed at all.
This is the xaml code:
<code>
<Grid Margin="0,88,0,338">
<adRotator:AdRotatorControl
        x:Name="AdRotator"
        AdHeight="100"
        AdWidth="640"
        LocalSettingsLocation="/defaultAdSettings.xml"
        RemoteSettingsLocation="http://retro-fan.de/WindowsPhone/DeguGuide/AdRotatorConfig.xml"
        AutoStartAds="True"
        IsTest="True"
        />
</Grid>
</code>
You can find the config at the specified location. The local defaultAdSettings.xml is identical.

Any suggestions?

**Comment by SimonDarksideJ** [comment]
Your probabilities are all set to ZERO.

No probability, no ad :dancer: 

Configure the probabilities accordingly and it should start.

**Comment by SimonDarksideJ** [comment]
On another note, you have identical configuration in each culture.  So in this case you only need the default culture.

You only need to specify other cultures if you want the configuration to be different.

**Comment by garv3** [comment]
Thank you for your answers!
There are not all probabilities set to zero. Admob ist set to 100 and I was not sure if the default culture is always taken if the given culture is not found or there is no culture available for some reason.
I have already tried to set other probabilities but unfortunately withoud success...

Any other suggestions?

**Comment by korzh** [comment]
I had a similar problem but then I realized that I didn't add the assemblies for ad providers I'm using (AdDuplex and pubCenter in my case).

**Comment by garv3** [comment]
That's true.i just found that AdMob is missing. I tried to download the Google AdMob SDK for WP8 and include it but when trying to set the reference to the DLL, I get an error message saying that I can not include it because the versions are not matching or the platform is wrong. I do not know the exact wording because I use the German version of VS and get German error messages.
I use Visual Studio Express 2013 and the projects target platform is set to Windows Phone 8.
So what now? 😡

**Comment by SimonDarksideJ** [comment]
There is a bug with the google wp8 control that can prevent it from being added.
To correct, edit the .cspoj file and add it manually

**Comment by garv3** [comment]
Ok, but how may I Add it? Simply edit the .csproj file and add something like this?
<Reference Include="GoogleAds">
    <HintPath>..\packages\Google AdMob\GoogleAds.dll</HintPath>
</Reference>
How should I know, how exactly AdMob is referenced?

**Comment by SimonDarksideJ** [comment]
Just place the dll in your project and copy one of the other reference links (the above one looks fine)

So long as the dll shows up in your project references then adrotator should find it fi e.

**Comment by garv3** [comment]
Works fine. Thanks!

**Comment by SimonDarksideJ** [comment]
Great news, please close the issue if it's resolved please
