### ISSUE TITLE
Installing AdRotator V2.1.0 Beta for Unity plugin

### ISSUE THREAD

**Issue by port119** [Adrotator/AdrotatorV2#22]
hi - I can't find a way to install the "AdRotator V2.1.0 Beta" in visual studio 2012 
(As per https://getadrotator.codeplex.com/releases/view/115850)
I believe I need the v2.1.0 Beta because of this error I'm getting in my windows phone 8 project:

Error   1   The type or namespace name 'Assets' does not exist in the namespace 'AdRotatorUnitySDK' (are you missing an assembly reference?)    

thanks,
warren

**Comment by SimonDarksideJ** [comment]
The V2 beta was pulled since we released the V2.0.0.0 stable release. (https://www.nuget.org/packages/AdRotator/)

The Unity plugin is broken at present, several welcome community devs are looking in to it at present
