### ISSUE TITLE
Universal Apps

### ISSUE THREAD

**Issue by Lorex75** [Adrotator/AdrotatorV2#23]
I was not able to get it work in Windows Phone Store (8.1) project in a Universal App solution; the Windows 8.1 version was installed without any problem while the WP 8.1 version didn't.

**Comment by SimonDarksideJ** [comment]
WP 8.1 apps are not supported by default at the moment, it is on our roadmap.  This is due to the changes in WP8.1.  Win8.1 isn't affected and it still works there.

**Comment by Lorex75** [comment]
Is there any workaround to get it worked now in WP 8.1, even manually? Thank you

**Comment by SimonDarksideJ** [comment]
You should be able to use the Windows 8 Source version in a WP81 project if you wish. 
just create a WP81 class library, link the code from the Win 8 version and reference the Core PCL.
Should work in a rough way.
Had a similar experience with other WP8/Win8 frameworks.  WP81 is closer to Win8 than WP8.

We will support it but cannot guarantee a timeline at the mo, sorry.

**Comment by Lorex75** [comment]
I'll start with the solution you mentioned probably these days and let you know if any issue may occure.
Many thnaks

**Comment by SimonDarksideJ** [comment]
Right, we actually have a branch (off my fork) with a possible Universal solution.
You can check it out here:
https://github.com/DDReaper/adrotatorv2/tree/Universal-8.1_upd

We are just testing this now and looking to incorporate it soon

**Comment by SimonDarksideJ** [comment]
Universal Support now released, pleas test and close if working. thanks

**Comment by pantonis** [comment]
Just tried it on a universal WP8.1 app. How can I enable google admob. it seems that their dll does not support Windows Phone 8.1.

**Comment by SimonDarksideJ** [comment]
Hi @pantonis I'll have to check.
You should be able to use their 8.0 dll but Google are horrendously slow in changing / updating Windows DLL's
Be sure you have marked the dll as "safe" when trying to add it to your project, by "unblocking" it in the file properties in Windows Explorer.

**Comment by pantonis** [comment]
Hi,
Thanks for your reply.
This is what I get when I add their dll in my project:

"The type 'System.Windows.Controls.UserControl' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Windows, Version=2.0.6.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'."

**Comment by SimonDarksideJ** [comment]
Gah, that's not going to work then as that all isn't compatible with wp81.
Will have to wait till google update their API or until we have our webapi interface up and running again.

You should still be able to deploy using just 8.0 which cross compiles to 8.1 when run

**Comment by pantonis** [comment]
Same problem with MobFox

**Comment by pantonis** [comment]
Your webapi interface? how is this working?

**Comment by SimonDarksideJ** [comment]
Doesn't surprise me about mobfox, or even Smaato.

In v1, we built a webapi interface that can grab ads from adprovider web interfaces. It was used for xna since almost no providers supported it.
It's in the cards to be re-engineered for v2, in a better/more configurable way. Plus ad support for WinJS scenarios.

It's still there in v1 if you want to try it

**Comment by pantonis** [comment]
I'll wait for the v2. Smaato supports WP8.1

**Comment by SimonDarksideJ** [comment]
Smaato support for all it's platforms was updated for the 2.1.1 release.
Please test and close the issue if ok.

**Comment by pantonis** [comment]
I have published my universal app using 2.1.0. Added Smaato and adduplex. No problems as of now. Seems to be working

**Comment by SimonDarksideJ** [comment]
Great, close the issue if your happy then :dancer:
