### ISSUE TITLE
Crash on winphone with Unity packpage

### ISSUE THREAD

**Issue by huuhau** [Adrotator/AdrotatorV2#24]
Hi team,
I downloaded both of your packages from this site: https://getadrotator.codeplex.com/releases/view/115850 , then add them to a new project and try to show ads on emulator. I followed these steps, include steps in readme file(same as this link https://github.com/Adrotator/AdrotatorV2/issues/9) but seems that it still not work. I keep PubCenter and removed other ads in defaultAdSettingsWP8.xml

After game started, a black screen appears at Unity logo and before ads buttons appear, game get crash with this exception:
System.Reflection.TargetInvocationException was unhandled
Message: An unhandled exception of type 'System.Reflection.TargetInvocationException' occurred in System.Windows.ni.dll

Can you guys have a look and show me what did I wrong?
Another question is can I change it to Admob? And can I test on my emulator, or have to build it on real device?
Thank you :)

My defaultAdSettingsWP8.xml:
< PubCenter AppId="test_client" SecondaryId="Image480_80" Probability="100" />

**Comment by SimonDarksideJ** [comment]
Unity broke our implementation in one of the recent upgrades and we haven't had time to fix it, sorry.

Another team have been looking at it but haven't reported back yet (which reminds me I must chase them).
TBH, I'm surprised you managed to get it to build as the current V2 update was incompatible with the current asset.
Will try and find some time to resolve this sometime soon.

In the meantime you can still implement the control manually in the WP / Win 8 project, you just wont have direct control from Unity. (unless you add a simple bridge)

**Comment by huuhau** [comment]
Thanks for your quick reply! That's what i'm afraid since last update is 8 months ago. Hope that you can back with it soon :D
As your reply, I followed readme and added that again for my project (just PubCenter), but it appears a black rectangle at the center of screen in about 2-3 seconds then disappeared. Is there anything wrong with it? and how can I control when can I show banner or not? Currently I still don't know how to create bridge between Unity and WP project :(
Another problem is when I change from PubCenter to Admob, nothing display on screen (added admob lib to references) even the black rectangle

**Comment by SimonDarksideJ** [comment]
I'd try a separate clean project to test your ads in, be aware that AdProviders may not actually deliver ads at times,  could be your AdUnit ID's or your account.  It is a really weird situation.

So what we recommend is to test the native control in your project with your AdUnit ID's (effectively not using AdRotator) just to test you are receiving Ads.
Then once it's working, switch to AdRotator to deliver them.

Note we just spotted a minor issue in the readme, in that the code for pubcentre that goes in the page constructor needs to point at the named instance of the control in XAML (same name) not the static reference.  Minor doc issue when it got published that we hope to correct very soon.

Try using the test values for the providers to just test AdPlacement

Here is a test project for you to examine 
https://www.dropbox.com/s/gqa8hcxnna39p17/AdRotatorDualPageTest.zip?dl=0

**Comment by huuhau** [comment]
Thank you very much. I will download your example and try to implement in my project ^^

About Adunit ID, I'm using test PubCenter ID config
(< PubCenter AppId="test_client" SecondaryId="Image480_80" Probability="100" />) 
and Admob ID that works normally when build on Android and iOS, so I don't think I have wrong ID here.

**Comment by huuhau** [comment]
It's me again ^^"
I found that you have just update this plugin, but after install it to a new project, I got same crash as before. Can you please help me have a look at it?

An exception of type 'System.NullReferenceException' occurred in AdRotator.DLL but was not handled in user code
Additional information: Object reference not set to an instance of an object.
After that, it crash at System.Windows.ni.dll!System.Windows.Threading.DispatcherOperation.Invoke()
Here is my build:
https://www.dropbox.com/s/czaujdp820in3r5/test_wp.rar?dl=0

That's weird that sometimes I don't rebuild or change anything, just run and that ads displayed @@, but success rate is very low

**Comment by SimonDarksideJ** [comment]
Right, finally got time to test this morning and the news isn't good.

1st, I did find a minor clean up issue that was causing that exception. So will do a patch fix for that.
2nd However in testing I did find one very silly issues on behalf of google.  The version of the DLL you are using (the latest) does NOT have an ARM variant, it only compiles with x86 or AnyCPU.

So basically have made it so this version of the control cannot be deployed to Windows Phone.  Going to check and see if I can find an older version that does.

**Comment by SimonDarksideJ** [comment]
Gah, no scratch that, silly me.  The demo version only came with compiled DLL's, not source.  You hadn't built for arm so it couldn't find it.

Will push out the patch fix today if I can

**Comment by SimonDarksideJ** [comment]
Version 2.0.2 pushed to NuGet, should be available to test with now.
Tested on device her using your project and works fine.
Hope this helps

**Comment by huuhau** [comment]
thanks man. so I just need to install from NuGet, and nothing change from Unity package, right?
I will check and give feedback ASAP :)

**Comment by huuhau** [comment]
I have just tested it. seems that only AdDuplex appears on my side but not other providers. But at least it doesn't crash :P. So I will close this issue here. Thanks for your great support ^^
