### ISSUE TITLE
AdMob not working on WP7

### ISSUE THREAD

**Issue by abdhoms** [Adrotator/AdrotatorV2#28]
I'm aware that Google doesn't officially support WP7 but I saw Google.AdMob.Ads.WindowsPhone7.dll in the AdProviderControl folder and I'm using it. 

However, I couldn't get it to work. Any help?

**Comment by SimonDarksideJ** [comment]
We should remove that now.  Google have stated they don't accept requests from WP7 apps/devices now
It did for a while so we left it in.

As with any provider issue, we recommend testing the provider on its own without AdRotator just to check if it's the provider dll/config that is causing the issue first.

**Comment by SimonDarksideJ** [comment]
Did this answer your question, if so can you close the issue?
