### ISSUE TITLE
Windows 8.1 support for AdRotator not working

### ISSUE THREAD

**Issue by SimonDarksideJ** [Adrotator/AdrotatorV2#30]
When deploying AdRotator on to a Windows 8.1 client with Unity, it fails with a null exception.

This is caused by Windows 8.1 using a different SwapChainBackground component for the canvas.

We'll resolve this shortly

**Comment by negue** [comment]
This also happens without using Unity. 

Edit: Sorry seems was to be my fault , forgot the code behind line.

**Comment by SimonDarksideJ** [comment]
We've fixed this now in the upcoming update (release 2.1) however we holding off for a bit due to issue #37 so we can ensure the integration works as expected.

**Comment by SimonDarksideJ** [comment]
2.1 release is now out. Please retest and close if working.
Thanks
