### ISSUE TITLE
Can't see any ads

### ISSUE THREAD

**Issue by baolanlequang** [Adrotator/AdrotatorV2#31]
Hi, I've added AdRotator with my unity game, I'm using AdMob but I cannnot see any ads display. I've configured ads position is "Top Center", ads size is "Leaderboard" and sliding ads is "none".

**Comment by SimonDarksideJ** [comment]
Can you check your AdUnity ID configuration using AdMob in a separate project without AdRotator.

We usually recommend testing this to ensure it's an issue with AdRotator and not the AdProvider control or config.

**Comment by SimonDarksideJ** [comment]
We've just been made aware of a limitation in the current asset, that the AdRotatorManagement GO needs to be added to the first scene.
This has been logged as issue #37 
If this solves your problem, please close this issue and we'll look to enhancing the capability.

**Comment by baolanlequang** [comment]
I've tested in WP8.1, maybe AdRotator have not supported this version yet?

**Comment by SimonDarksideJ** [comment]
Yes, Win 8.1, Wp 8.1 and Universal apps will be fully supported in the upcoming 2.1 release only.

**Comment by SimonDarksideJ** [comment]
The 2.1 release is now out.  Can you update and test, if working please close the issue

**Comment by baolanlequang** [comment]
Can you give me the link? I can't find any link of the 2.1
