### ISSUE TITLE
Local DefaultHouseAd not working -- simple mistake?

### ISSUE THREAD

**Issue by ghost** [Adrotator/AdrotatorV2#36]
I'm getting the following error using v2.0.2:
https://github.com/Adrotator/AdrotatorV2/blob/develop/AdRotator/DefaultHouseAd.cs#L67

```
Failed to resolve DefaultAd Class definition - not found
```

My project is Windows Phone Silverlight 8.1 (note: Silverlight). I created a brand new project to test and am still getting the error. The following does not work:

```
<DefaultHouseAd SecondaryId="PhoneApp1.LocalAdTestControl1"/>
```

If I add an AppId, I get the same error for the SecondaryId, but successfully load the XAML from the AppId (so I know it's not a display/visibility issue):

```
<DefaultHouseAd AppId="http://adrotator.apphb.com/SampleRemoteHouseAd.xaml" SecondaryId="PhoneApp1.LocalAdTestControl1"/>
```

LocalAdTestControl1 is in the root directory of the project. Am I referencing it wrong? I'm assuming I'm making some kind of simple mistake. I've searched around with no luck.

I've uploaded the sample project with the error:
https://github.com/Rardor/AdRotatorHouseAdError

**Comment by SimonDarksideJ** [comment]
We had a PR submitted related to the house ad sometimes not being detected properly.
Try re-testing in our upcoming 2.1 release and see if that resolves the issue.

**Comment by ghost** [comment]
Thanks for the quick response. What's the best way for me to follow version numbers and see when there's an update? Nuget?

**Comment by SimonDarksideJ** [comment]
Our primary distribution method is NuGet, so you can check there (currently v2.02)
Or you could subscribe to the AdRotator blog at getadrotator.com

**Comment by SimonDarksideJ** [comment]
2.1 release is now up on NuGet, please test and if fixed, close this issue please.

**Comment by ghost** [comment]
Great! I tested and the house ads seem to be working in 2.1.

Thank you!
