### ISSUE TITLE
Perhaps a stupid issue about the nuget package

### ISSUE THREAD

**Issue by jphellemons** [Adrotator/AdrotatorV2#4]
But I cannot find it.

http://www.nuget.org/packages?q=adrotator

http://www.nuget.org/packages?q=adrotatorv2

**Comment by Pepsi1x1** [comment]
Have you selected to include pre-release packages?

http://www.nuget.org/packages?q=adrotator&prerelease=true&sortOrder=relevance

shows up http://www.nuget.org/packages/AdRotator/2.1.0-Beta1

**Comment by SimonDarksideJ** [comment]
Yup @Pepsi1x1  is comletely right there.
Just searching http://www.nuget.org/packages?q=adrotator will only show up the ld V1 AdRotator project. Can still be used, just doesn't have the newer features of V2 but still supports House Ads

**Comment by jphellemons** [comment]
It had to do with the downtime nuget had a few days ago, thanks though!
