### ISSUE TITLE
Support new Smaato SDK for Windows 8.1 & WP 8.x

### ISSUE THREAD

**Issue by linderboss** [Adrotator/AdrotatorV2#41]
Finally Smaato is updating their SDK for WP 8 and released a Nuget package supporting Windows Store apps as well!

http://www.nuget.org/packages/SOMAW81_Package/

Will be nice to have an alternative to PubCenter for Windows Store apps.

**Comment by SimonDarksideJ** [comment]
Thanks for spotting that, will update our info.
Will patch the supported ad provider list soon

**Comment by SimonDarksideJ** [comment]
The updated 2.1.1 release includes support for Smaato on all it's new platforms and the NuGet package.

Hope this helps and if it's ok, please close this issue

**Comment by linderboss** [comment]
Nice!
