### ISSUE TITLE
need help setting up Ad Provider specific DLL's

### ISSUE THREAD

**Issue by illogicalgames** [Adrotator/AdrotatorV2#42]
hi, im a total noob with vs. previously i use the prerelease adrotator v2, they already set up adduplex in the nuget package so i dont need to install it by myself, now with the 2.10 release, they dont include the dlls in the package anymore, so im total lost where to begin.

currently i am able to build the unity project and run the game, displaying the adrotator. but i failed to make it display the real ad. im using unity, now i have setup the defaultadsetting.xml and when i build the unity project, i open the vs project and import the nuget package, im able to run the game with adrotator, but the ad always display the defaulthousead for wp7. i cant make it work to display adduplex and my admob. and also how to install the admob dll and/or other ad provider.

i need help. please direct me steps by steps because im not very good with programming and vs.

**Comment by SimonDarksideJ** [comment]
Instructions were posted here - http://getadrotator.com/enter-adrotator-v2/

But in short:
1: Install AdRotator via NuGet
2: Install adproviders (either via NuGet, their SDK, or DLL from their site)
(AdDuplex no longer supports NuGet for their latest releases so you need to download their SDK from their site!)
3: Add XML Namespace to page you want AdRotator on (example in readme)
4: Add XAML control to page (example in readme)
5: Configure XML file with installed providers in project
(optional) put your XML Config on a website somewhere and update the Remote property, or just remove it from the XAML

Hope that helps.

**Comment by illogicalgames** [comment]
Hi DDReaper,
thank you so much for your reply. i really glad that someone could help me with this. i've been stuck here for couple of days now.

i did download the adduplex sdk from here,
https://visualstudiogallery.msdn.microsoft.com/92f919ee-40a8-4549-8768-d3b453ceebea
 i run the installation, and then how to import the sdk into my vs project? u see, this is what im dealing with, im total noob with vs and dlls. im sorry for wasting your time, but i really need to make this work.

btw, im using Unity, I have successfully integrated the unity package and when I run, I can see the ad, and can close it whenever I wanted. only thing left is the adprovider. I dont understand the readme in the adrotator package.

**Comment by SimonDarksideJ** [comment]
Oh no worries, happy to help

To add AdDuplex (or Pubcenter) simply right click on "references" and select "add reference" then in one of the branches (reference assemblies under windows I think) you will find installed sdk references.

For other providers where you download them, use the browse button to locate the dll

When done click add/finish

**Comment by illogicalgames** [comment]
Hi, thank you for your reply. after i have added the reference, im confuse with the part

***For Unity, add the following in your App.XAML.cs constructor, as follows:
    //PubCenter
    AdRotatorUnitySDK.Integration.AdRotatorBridge.PlatformAdProviderComponents.Add(AdRotator.Model.AdType.PubCenter, typeof(AdControl)); //<- Resolve to Microsoft AdControl
    //AdDuplex
    AdRotatorUnitySDK.Integration.AdRotatorBridge.PlatformAdProviderComponents.Add(AdRotator.Model.AdType.AdDuplex, typeof(AdControl)); //<- Resolve to AdDuplex AdControl

i dont understand what does add following in app.xaml.cs constructor mean. i tried copy and pasted the code in app but it gives me error.

**Comment by SimonDarksideJ** [comment]
Right, so your using adrotator via Unity 😎 
This video may help https://www.dropbox.com/s/qflicxvzimfnolw/AdRotatorUnityIntro.mp4?dl=0

For the extra bits, you need to right click on the "AdControl" parts and select resolve for the correct provider (pubcenter or adduplex)

All detailed in the video

Hope that helps

**Comment by illogicalgames** [comment]
Hi, thank you for your super fast reply!! im getting there now. but when i copied the code into the app.xaml.cs, im getting "type or namespace "AdControl could not be found, are you using...""

and "AdRotator" doesnot exist in the current context

i tried right clicking on it as you said, but i dont see any "resolve" option. hmmm

**Comment by illogicalgames** [comment]
ahh I found it! I have to copy the app.xaml and main.xaml into the windows.phone folder. thank you very much. you helped me a lot! ahh

**Comment by SimonDarksideJ** [comment]
Thanks if you are running would you mind closing the issue :dancer:

**Comment by illogicalgames** [comment]
sure. thanks for your help
