### ISSUE TITLE
System.UnauthorizedAccessException in IsolatedStorage in AdRotator V2.1

### ISSUE THREAD

**Issue by Nirmal4G** [Adrotator/AdrotatorV2#46]
Whenever I run my WP71 project in WP71 Emulator or WP8 Emulator I get this error saying that the file is read-only and cannot perform write operations.

The project is working with V2.0, V2.0.1! but not recent versions!

Please fix it...!

**Comment by SimonDarksideJ** [comment]
That is such an odd error.  Sounds like a capabilities issue.

Could you post the exact error / stack trace so we can look in to this further?
