### ISSUE TITLE
need help setting up AdRotator to work

### ISSUE THREAD

**Issue by CoolRunnings** [Adrotator/AdrotatorV2#47]
hi,
i'm new with AdRotator and i have some Problems with showing ads some times.

My Usercontrol

```
...
    <Grid>
        <adRotator:AdRotatorControl x:Name="AdRotatorUC"
            AdHeight="{Binding ElementName=UCAdRotator, Path=RowSpan}"
            AdWidth="{Binding ElementName=UCAdRotator, Path=ColSpan}"
            LocalSettingsLocation="{Binding ElementName=UCAdRotator, Path=LocalSettingsFile}"
            RemoteSettingsLocation="{Binding ElementName=UCAdRotator, Path=RemoteSettingsFile}"
            IsAdRotatorEnabled="True"
            AutoStartAds="True" 
            Margin="0,0,0,0"
            HorizontalAlignment="Left" 
            VerticalAlignment="Top" />
    </Grid>
```

the codebehind Looks like

```
...
        public string LocalSettingsFile
        {
            get { return (string)GetValue(LocalSettingsFileProperty); }
            set { SetValue(LocalSettingsFileProperty, value); }
        }
        public static readonly DependencyProperty LocalSettingsFileProperty = DependencyProperty.Register("LocalSettingsFile", typeof(string), typeof(AdRotatorUserControl), new PropertyMetadata(null));

        public string RemoteSettingsFile
        {
            get { return (string)GetValue(RemoteSettingsFileProperty); }
            set { SetValue(RemoteSettingsFileProperty, value); }
        }
        public static readonly DependencyProperty RemoteSettingsFileProperty = DependencyProperty.Register("RemoteSettingsFile", typeof(string), typeof(AdRotatorUserControl), new PropertyMetadata(null));
...
        public AdRotatorUserControl()
        {
            this.InitializeComponent();

            AdRotatorUC.PlatformAdProviderComponents.Add(AdRotator.Model.AdType.PubCenter, typeof(Microsoft.Advertising.WinRT.UI.AdControl));
            AdRotatorUC.PlatformAdProviderComponents.Add(AdRotator.Model.AdType.AdDuplex, typeof(AdDuplex.Universal.Controls.Win.XAML.AdControl));
            AdRotatorUC.PlatformAdProviderComponents.Add(AdRotator.Model.AdType.Smaato, typeof(SOMAW81.AdViewer));

#if DEBUG
            AdRotator.AdRotatorControl.Log += (s) => System.Diagnostics.Debug.WriteLine(s);
#endif

        }

```

the Usercontrol is included via datatemplate in some pages in different Folders like that:

```
    <DataTemplate x:Key="AdvertisingTemplate">
        <Grid Width="{Binding ColSpan}" Height="{Binding RowSpan}" Background="Chocolate" Margin="2" >
            <StackPanel Background="{StaticResource ApplicationPageBackgroundThemeBrush}" Orientation="Vertical">
                <UserControls:AdRotatorUserControl ColSpan="{Binding ColSpan}" RowSpan="{Binding RowSpan}"
                                                   LocalSettingsFile="{Binding LocalSettingsFile}" 
                                                   RemoteSettingsFile="{Binding RemoteSettingsFile}"/>
            </StackPanel >
        </Grid>
    </DataTemplate>
```

the configuration file is:

```
<?xml version="1.0" encoding="utf-8"?>
<AdSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <CultureDescriptors CultureName="de-DE">
    <PubCenter AppId="dabb12be-c2f0-..." SecondaryId="19..." Probability="20" AdOrder="1"/>
    <AdDuplex AppId="12..." Probability="30" AdOrder="1"/>
    <Smaato AppId="92..." SecondaryId="65..." Probability="50" AdOrder="1"/>
  </CultureDescriptors>
  <CultureDescriptors CultureName="en-US">
    <PubCenter AppId="dabb12be-c2f0-..." SecondaryId="19..." Probability="50" AdOrder="1"/>
    <AdDuplex AppId="12..." Probability="30" AdOrder="1"/>
    <Smaato AppId="92..." SecondaryId="65..." Probability="20" AdOrder="1"/>
  </CultureDescriptors>
  <CultureDescriptors CultureName="">
    <PubCenter AppId="dabb12be-c2f0-..." SecondaryId="19..." Probability="35" AdOrder="1"/>
    <AdDuplex AppId="12..." Probability="35" AdOrder="1"/>
    <Smaato AppId="92..." SecondaryId="65..." Probability="30" AdOrder="1"/>
  </CultureDescriptors>
</AdSettings>
```

I have tried all constellations with local and remote Settings file. 
In the mainview in the root-folder the ads are showing for the first time.
in the Detail/subviews in subfolders i got the following message from the log Event:

```
Control {0} - Trying provider None
```

If i navigate back to the mainview, the same message appears!

What am I doing wrong?

Must the Settings file stay also in the subfolders of the different views where i have the usercontrol included?

If i use only remote Settings the same message appears.

Thanks for help in advance!

**Comment by SimonDarksideJ** [comment]
Have you tried a basic implementation first.
I suspect you likely have a binging issue with the configuration file XML settings.  Although Can't see anything specifically wrong with your implementation.

First verify you have ads by adding the control directly to a page first and then have a look at the bindings.  If it works normally but not with the bindings can you package a sample project and we'll investigate further

**Comment by CoolRunnings** [comment]
Thank you for that Information, that my implementation looks not wrong. So i will check all bindings and come back with the new status.

**Comment by CoolRunnings** [comment]
Hi Mr DDReaper,
i'v made an sample universal app with mvvm pattern. I only implemented the Windows store part. The same Problem as i descript above.
Here are the sample app: [Download link](http://1drv.ms/1rUIyyb)
Thank you for your help!!!

**Comment by CoolRunnings** [comment]
Hi Simon,
have you time to take a look at the sample app?
Thank you.

**Comment by SimonDarksideJ** [comment]
Apologies @CoolRunnings we've been slammed this last week, will try to get to it over the Christmas week :D

**Comment by robwirving** [comment]
Hi @CoolRunnings,
I was able to take a look at your sample app. When you initialize the AdRotator control you need to tell it which AdProvider types you'll be using. This is necessary for the way we have reflection setup. I was able to fix your sample application by adding the following line to your MainPage constructor:
AdRotatorDirect.PlatformAdProviderComponents.Add(AdRotator.Model.AdType.AdDuplex, typeof(AdDuplex.Universal.Controls.Win.XAML.AdControl));

@DDReaper we probably need to document this better somewhere.

**Comment by SimonDarksideJ** [comment]
Hi @coolrunnings
See Rob's comment above.

For WinRT components you have to do the additional step to register WinRT component dll's (currently adduplex & pubcenter)

This is highlighted in the readme when you install the control from NuGet

Can you test and if this resolves your problem could you close the issue

**Comment by CoolRunnings** [comment]
Great work again! 
Thank you two guy's for helping me.
Wish you both a nice time.
