### ISSUE TITLE
work in Silverlight but not in Universal App

### ISSUE THREAD

**Issue by thkaw** [Adrotator/AdrotatorV2#49]
Hi, 
I encounter a problem,
When I using Adrotator V2(2.1.1) in Windows Phone 8.1 Silverlight Project wasn't any problem.
And Designer screen will show: "AdRotator in design mode, No ads will be displayed"
![2014-12-08_12-13-56](https://cloud.githubusercontent.com/assets/1552721/5334747/afe4bc6c-7ed3-11e4-8c75-a6dcdc7dbb70.png)

Every Ad functional are ok.

But When I using Universal App Project, either WindowsPhone or Windows 8,
In Designer Mode is blank without any text show:
![2014-12-08_12-16-53](https://cloud.githubusercontent.com/assets/1552721/5334754/142077c0-7ed4-11e4-8653-2c158d127b10.png)

So it can't show any ad content.

Any help?
Thanks!

**Comment by SimonDarksideJ** [comment]
Hmm, must be an issue in the way that Universal Phone apps detect the designer.
No worries, it still works in run time mode, you can try adding a border around the AdControl to place it in blend then remove it for release (copying placement settings as required).

We'll have a look at the designer support for universal apps

**Comment by CoolRunnings** [comment]
Am 08.12.2014 um 14:27 schrieb Simon (Darkside) Jackson:

> Hmm, must be an issue in the way that Universal Phone apps detect the
> designer.
> No worries, it still works in run time mode, you can try adding a border
> around the AdControl to place it in blend then remove it for release
> (copying placement settings as required).
> 
> We'll have a look at the designer support for universal apps
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Adrotator/AdrotatorV2/issues/49#issuecomment-66115285.
> 
> Hi Simon,

thank you so much for your answer. I'll develop now the app and still
come back to adrotator at the end.

Thank you and you and your familie a very nice christmas time.

Stefan

**Comment by thkaw** [comment]
Thanks for replied :), this component still working although not showing notice text in designer.
