### ISSUE TITLE
Only one local configuration file can be used per app

### ISSUE THREAD

**Issue by Pepsi1x1** [Adrotator/AdrotatorV2#5]
On line 57 of AdRotator/AdRotatorComponent.cs, AdSettings _settings is declared as static, which means that only one local ad configuration is used during the lifetime of the app, whichever one is his first in the flow.

Although private async Task LoadAdSettings() checks for a new remote file every time, it also performs a null check on _settings before loading local configs, which means that if there are multiple instances of the component used throughout the app, only the config for the first component is used throughout all instances.

So either the static keyword should be removed or the null checks, i propose the former.

**Comment by SimonDarksideJ** [comment]
Hmm, I thought we had already covered and tested this.  We do / did have a sample showing multiple controls on the same page.  Granted cannot remember if it was using different config files.

What cases can you suggest where multiple config files would be needed?

**Comment by Pepsi1x1** [comment]
In my app photograffiti using the PubCenter provider I have a different ad unit per page in the app, this has the side effect of producing some analytics for us. Which means a separate config per page.

Sent from my Windows Phone

**Comment by Pepsi1x1** [comment]
I've now switched to using one ad unit throughout the app and am using Flurry for analytics

**Comment by SimonDarksideJ** [comment]
OK, well if you believe it resolved can you close the issue.  Or is using multiple config files still not working?

**Comment by Pepsi1x1** [comment]
It still doesn't work, I have just changed my usage due to it being broken.

**Comment by SimonDarksideJ** [comment]
Hmm, OK will look in to that in the upcoming fixes.  For now I know that multiple offline config files works
