### ISSUE TITLE
PubCenter never shows WP8 (v2.1.1)

### ISSUE THREAD

**Issue by gintechsystems** [Adrotator/AdrotatorV2#56]
This may be my fault, but I have tried multiples things. I am using Visual Studio 2013 and have used v1 with no issues, switched to v2 because of all the improvements but it seems PubCenter never shows up for me, only Smaato.

I have made sure my probabilities are set and PubCenter is higher than Smaato. I tried removing Smaato and now no ads show. I have imported the following DLL name for PubCenter: "Microsoft Advertising SDK for Windows Phone 8 (Silverlight)".

I have also added the following line of code just to try:

screenAd.PlatformAdProviderComponents.Add(AdRotator.Model.AdType.PubCenter, typeof(Microsoft.Advertising.Mobile.UI.AdControl));

Is this all correct? What am I missing or is this a bug?

**Comment by gintechsystems** [comment]
Nevermind, I had my appId & SecondaryId swapped!! Ugh.

**Comment by SimonDarksideJ** [comment]
No worries @gintechsystems I do need some better guidance in the project about configuring ID's. 
Will include it in the next update

**Comment by gintechsystems** [comment]
Thanks again, I have done this multiple times before but for some reason I must of swapped them and did not realize it, I tried all the difficult what ifs and finally got to the simplest one, IDs.
