### ISSUE TITLE
ad refresh issue

### ISSUE THREAD

**Issue by jphellemons** [Adrotator/AdrotatorV2#6]
it looks similar to this :
https://getadrotator.codeplex.com/workitem/16

when I set 

``` csharp
AdRotatorControl.AdRefreshInterval = 15;
```

(which should be an int)
I get this message:

> Additional information: '15' is not a valid value for property 'AutoStartAds'.

I have this in my xaml 

``` xml
AutoStartAds="True"
```

which works without the adrefreshinterval in the code behind.

and a slightly offtopic thing: my other issue regarding the nuget package can be closed. It had to do with the nuget issues from yesterday https://twitter.com/nuget/status/451781673269473280

**Comment by LouWii** [comment]
Just take a look at the documentation
http://getadrotator.com/windowsphone/

The minimum value is 60.

**Comment by jphellemons** [comment]
please view line 122

![2014-04-08 15_36_15-zaklamp release_mixed platforms debugging - microsoft visual studio](https://cloud.githubusercontent.com/assets/1119134/2644144/9b48c86c-bf24-11e3-840e-c51a42ffeb49.png)

**Comment by SimonDarksideJ** [comment]
Lol, AutoStartAds is a boolean.
Granted, this shouldn't crash AdRotator so we will have to add some protection against that.
It's safeguarded through XAML in the dependency property, but looks like we missed it through code
_HeadSlap_

The adrefreshinterval property default value is 60.
