### ISSUE TITLE
Adrotator crash

### ISSUE THREAD

**Issue by jphellemons** [Adrotator/AdrotatorV2#9]
I have added the somawp8.dll for smaato and the mobfox dll for mobfox.ads
This is my XAML (nothing special here)

``` xml
<adRotator:AdRotatorControl 
                x:Name="AdRotatorControl" 
                Width="480" 
                Height="80"
                AdHeight="80"
                AdWidth="480"
                AutoStartAds="True"
                LocalSettingsLocation="app.xml"
                RemoteSettingsLocation="http://mydomain.com/app.xml"/>
```

and this is my c# code behind it

``` C#
void MainPage_Loaded(object sender, System.Windows.RoutedEventArgs e)
 {           AdRotatorControl.PlatformAdProviderComponents.Add(AdRotator.Model.AdType.PubCenter, typeof(Microsoft.Advertising.Mobile.UI.AdControl));
                        AdRotatorControl.PlatformAdProviderComponents.Add(AdRotator.Model.AdType.MobFox, typeof(MobFox.Ads.AdControl));
            AdRotatorControl.Log += AdRotatorControl_Log;
        }

        void AdRotatorControl_Log(string message)
        {
            Console.WriteLine(message);
        } 
```

and I also tried to comment out the mobfox line, but bugsense gave me this stacktrace:

> MS.Internal.WrappedException: The type initializer for 'MobFox.Ads.AdProviders.0' threw an exception. ---> System.TypeInitializationException: The type initializer for 'MobFox.Ads.AdProviders.0' threw an exception. ---> System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
> at Microsoft.Phone.Info.ExtendedPropertiesHelper.GetValue(String propertyName, GetValueImplDelegate getValueImpl)
> at Microsoft.Phone.Info.DeviceExtendedProperties.GetValue(String propertyName)
> at MobFox.Ads.AdProviders.0..cctor()
> --- End of inner exception stack trace ---
> at MobFox.Ads.AdProviders.0.5()
> at MobFox.Ads.AdControl.OnApplyTemplate()
> at System.Windows.FrameworkElement.OnApplyTemplate(IntPtr nativeTarget)
> --- End of inner exception stack trace ---
> --- Inner exception of type System.TypeInitializationException start ---
> --- Message: The type initializer for 'MobFox.Ads.AdProviders.0' threw an exception. ---
> System.TypeInitializationException: The type initializer for 'MobFox.Ads.AdProviders.0' threw an exception. ---> System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
> at Microsoft.Phone.Info.ExtendedPropertiesHelper.GetValue(String propertyName, GetValueImplDelegate getValueImpl)
> at Microsoft.Phone.Info.DeviceExtendedProperties.GetValue(String propertyName)
> at MobFox.Ads.AdProviders.0..cctor()
> --- End of inner exception stack trace ---
> at MobFox.Ads.AdProviders.0.5()
> at MobFox.Ads.AdControl.OnApplyTemplate()
> at System.Windows.FrameworkElement.OnApplyTemplate(IntPtr nativeTarget)
> --- End of inner exception stack trace ---
> --- Inner exception of type System.UnauthorizedAccessException start ---
> --- Message: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED)) ---
> System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
> at Microsoft.Phone.Info.ExtendedPropertiesHelper.GetValue(String propertyName, GetValueImplDelegate getValueImpl)
> at Microsoft.Phone.Info.DeviceExtendedProperties.GetValue(String propertyName)
> at MobFox.Ads.AdProviders.0..cctor()
> --- End of inner exception stack trace ---

it is on a windows phone 8 by the way. What is my mistake?

**Comment by SimonDarksideJ** [comment]
Can you also post your config xml please (app.xml)

**Comment by jphellemons** [comment]
Sure. I took out my tokens and filled in pseudo stuff (myappid, ad id, publisher id)

``` xml
<?xml version="1.0" encoding="utf-8"?>
<AdSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <CultureDescriptors CultureName="">
    <Smaato AppId="MYAPPID" SecondaryId="PUBLISHER ID" Probability="40"/>
    <PubCenter AppId="MYAPPIP" SecondaryId="AD ID" Probability="20"/>
    <MobFox AppId="MYAPPID" IsTest="false" Probability="40"/>
    </CultureDescriptors>
</AdSettings>
```

**Comment by SimonDarksideJ** [comment]
Odd, Can't seem to replicate the issue here.
As MobFox seems to be the one crashing, can you try just using Smaato (latest version) and PubCentre?

**Comment by jphellemons** [comment]
Perhaps I have the wrong DLL's referenced? 
![2014-04-25 15_30_38-reference manager - zaklamp](https://cloud.githubusercontent.com/assets/1119134/2801098/d4bb0248-cc7d-11e3-9aa9-ed972432b5f5.png)

googleads 6.5.11.0
mobfox.ads 1.3.98.46815
somawp8 1.1.4993.33865
microsoft.advertising.mobile 6.2.960.0
microsoft.advertising.mobile.ui 6.2.960.0
Microsoft Advertising SDK for Windows Phone 8 (XAML) 6.1.0.0

adrotator 2.1.0 (pre release)

**Comment by SimonDarksideJ** [comment]
Could you ensure you are using only one version of the Microsoft 
Pubcenter advertising SDK, you seem to have two assigned and see if that 
helps.

Plus what is the exception text you are receiving

Simon

**Comment by jphellemons** [comment]
Removing the 6.1 works in my project. But in an other (similar) project it fails in the code behind at the first reference of the control:

``` csharp
void MainPage_Loaded(object sender, RoutedEventArgs e)
{
    AdRotatorControl.PlatformAdProviderComponents.Add(AdRotator.Model.AdType.PubCenter, typeof(Microsoft.Advertising.Mobile.UI.AdControl)); // crash this line
    AdRotatorControl.Log += AdRotatorControl_Log;
}

void AdRotatorControl_Log(string message)
{
     Console.WriteLine(message);
}
```

Object reference not set to an instance of an object.
not much stacktrace. Can it be related that I have more adproviders in my xml then I added to the platformadprovidercomponents? somehow AdRotatorControl is null?

and in my main project it keeps crashing at mobfox (smaato and pubcenter work)
It does not crash on this line:

```
AdRotatorControl.PlatformAdProviderComponents.Add(AdRotator.Model.AdType.MobFox, typeof(MobFox.Ads.AdControl));
```

but the app just quits. This is what bugsense told me:

> MS.Internal.WrappedException: The type initializer for 'MobFox.Ads.AdProviders.0' threw an exception. ---> System.TypeInitializationException: The type initializer for 'MobFox.Ads.AdProviders.0' threw an exception. ---> System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
> at Microsoft.Phone.Info.ExtendedPropertiesHelper.GetValue(String propertyName, GetValueImplDelegate getValueImpl)
> at Microsoft.Phone.Info.DeviceExtendedProperties.GetValue(String propertyName)
> at MobFox.Ads.AdProviders.0..cctor()
> --- End of inner exception stack trace ---
> at MobFox.Ads.AdProviders.0.5()
> at MobFox.Ads.AdControl.OnApplyTemplate()
> at System.Windows.FrameworkElement.OnApplyTemplate(IntPtr nativeTarget)
> --- End of inner exception stack trace ---
> --- Inner exception of type System.TypeInitializationException start ---
> --- Message: The type initializer for 'MobFox.Ads.AdProviders.0' threw an exception. ---
> System.TypeInitializationException: The type initializer for 'MobFox.Ads.AdProviders.0' threw an exception. ---> System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
> at Microsoft.Phone.Info.ExtendedPropertiesHelper.GetValue(String propertyName, GetValueImplDelegate getValueImpl)
> at Microsoft.Phone.Info.DeviceExtendedProperties.GetValue(String propertyName)
> at MobFox.Ads.AdProviders.0..cctor()
> --- End of inner exception stack trace ---
> at MobFox.Ads.AdProviders.0.5()
> at MobFox.Ads.AdControl.OnApplyTemplate()
> at System.Windows.FrameworkElement.OnApplyTemplate(IntPtr nativeTarget)
> --- End of inner exception stack trace ---
> --- Inner exception of type System.UnauthorizedAccessException start ---
> --- Message: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED)) ---
> System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
> at Microsoft.Phone.Info.ExtendedPropertiesHelper.GetValue(String propertyName, GetValueImplDelegate getValueImpl)
> at Microsoft.Phone.Info.DeviceExtendedProperties.GetValue(String propertyName)
> at MobFox.Ads.AdProviders.0..cctor()
> --- End of inner exception stack trace ---

probably found the solution for the mobfox ads:
http://wpunifiedad.codeplex.com/discussions/436059
it needed more rights

**Comment by SimonDarksideJ** [comment]
The V2 project is designed to fail nicely in the event of having too many providers or bad references, so it is odd you are getting such an error.

What I might suggest if you are willing, is to clone the source for the project and reference that in your project (instead of the NuGet) and see where it is actually failing if possible.
If could be one of the providers have changed their interface but as I am unable to replicate it I am at a loss as to why.

**Comment by jphellemons** [comment]
Ok, thank you. Will update if I have more info

**Comment by Pepsi1x1** [comment]
It looks like you are missing some required capabilities for MobFox from your WMAppManifest.xml, can you post the ID_CAP section please.

**Comment by SimonDarksideJ** [comment]
If this issue is resolved, can you close the issue please @jphellemons ?
